/**
 * Task Schema for MongoDB
 * Defines the structure for tasks and to-do items in projects
 */

export enum TaskStatus {
  PENDING = 'pending',
  IN_PROGRESS = 'in_progress',
  BLOCKED = 'blocked',
  COMPLETED = 'completed',
  CANCELLED = 'cancelled'
}

export enum TaskPriority {
  LOW = 'low',
  MEDIUM = 'medium',
  HIGH = 'high',
  URGENT = 'urgent'
}

export enum TaskType {
  GENERAL = 'general',
  SUBMITTAL = 'submittal',
  RFI = 'rfi',
  INSPECTION = 'inspection',
  SAFETY = 'safety',
  MILESTONE = 'milestone',
  CUSTOM = 'custom'
}

export interface Task {
  _id: string; // MongoDB ObjectId
  projectId: string; // Project ObjectId

  // Task Details
  title: string;
  description?: string;
  type: TaskType;
  status: TaskStatus;
  priority: TaskPriority;

  // Assignment
  assignedTo: string[]; // Array of User ObjectIds
  assignedBy: string; // User ObjectId

  // Dates
  dueDate?: Date;
  startDate?: Date;
  completedDate?: Date;

  // Dependencies
  dependencies?: string[]; // Array of Task ObjectIds that must be completed first
  blockedBy?: string[]; // Array of Task ObjectIds that are blocking this task

  // Milestone Association
  milestoneId?: string; // Associated milestone from project

  // Auto-Generated Information
  autoGenerated: boolean; // True if generated by Python script
  generatedFrom?: {
    source: 'schedule' | 'milestone' | 'manual';
    scheduleId?: string;
    milestoneId?: string;
  };

  // Checklist (sub-tasks)
  checklist?: ChecklistItem[];

  // Attachments
  attachments?: {
    fileName: string;
    fileUrl: string;
    fileSize: number;
    uploadedBy: string; // User ObjectId
    uploadedAt: Date;
  }[];

  // Comments/Notes
  comments?: Comment[];

  // Metadata
  createdBy: string; // User ObjectId
  createdAt: Date;
  updatedAt: Date;
  tags: string[];
}

export interface ChecklistItem {
  id: string;
  text: string;
  completed: boolean;
  completedBy?: string; // User ObjectId
  completedAt?: Date;
}

export interface Comment {
  id: string;
  text: string;
  author: string; // User ObjectId
  createdAt: Date;
  updatedAt?: Date;
  edited?: boolean;
}

/**
 * MongoDB Schema definition
 */
export const TaskSchema = {
  projectId: { type: String, required: true },

  title: { type: String, required: true, trim: true },
  description: { type: String, trim: true },
  type: { type: String, enum: Object.values(TaskType), default: TaskType.GENERAL },
  status: { type: String, enum: Object.values(TaskStatus), default: TaskStatus.PENDING },
  priority: { type: String, enum: Object.values(TaskPriority), default: TaskPriority.MEDIUM },

  assignedTo: [{ type: String, required: true }],
  assignedBy: { type: String, required: true },

  dueDate: Date,
  startDate: Date,
  completedDate: Date,

  dependencies: [String],
  blockedBy: [String],

  milestoneId: String,

  autoGenerated: { type: Boolean, default: false },
  generatedFrom: {
    source: { type: String, enum: ['schedule', 'milestone', 'manual'] },
    scheduleId: String,
    milestoneId: String
  },

  checklist: [{
    id: String,
    text: String,
    completed: { type: Boolean, default: false },
    completedBy: String,
    completedAt: Date
  }],

  attachments: [{
    fileName: String,
    fileUrl: String,
    fileSize: Number,
    uploadedBy: String,
    uploadedAt: Date
  }],

  comments: [{
    id: String,
    text: String,
    author: String,
    createdAt: Date,
    updatedAt: Date,
    edited: { type: Boolean, default: false }
  }],

  createdBy: { type: String, required: true },
  createdAt: { type: Date, default: Date.now },
  updatedAt: { type: Date, default: Date.now },
  tags: [String]
};

// Indexes for performance
export const TaskIndexes = [
  { projectId: 1, status: 1 }, // For project task queries
  { assignedTo: 1, status: 1 }, // For user task queries
  { dueDate: 1 }, // For deadline sorting
  { priority: 1, status: 1 }, // For priority filtering
  { milestoneId: 1 }, // For milestone-based tasks
  { createdAt: -1 }, // For sorting by date
];
