/**
 * Database Schema for ConstructAid - PostgreSQL with Drizzle ORM
 */
import { pgTable, text, varchar, integer, timestamp, boolean, jsonb, serial, pgEnum } from 'drizzle-orm/pg-core';

// Enums
export const userRoleEnum = pgEnum('user_role', ['OWNER', 'ARCHITECT', 'GC', 'SUB', 'ADMIN']);
export const userStatusEnum = pgEnum('user_status', ['PENDING_VERIFICATION', 'ACTIVE', 'SUSPENDED', 'INACTIVE']);
export const projectStatusEnum = pgEnum('project_status', ['planning', 'bidding', 'pre_construction', 'in_progress', 'closeout', 'completed', 'on_hold']);
export const taskStatusEnum = pgEnum('task_status', ['pending', 'in_progress', 'blocked', 'completed', 'cancelled']);
export const taskPriorityEnum = pgEnum('task_priority', ['low', 'medium', 'high', 'urgent']);
export const taskTypeEnum = pgEnum('task_type', ['general', 'submittal', 'rfi', 'inspection', 'safety', 'milestone']);

// Users Table
export const users = pgTable('users', {
  id: serial('id').primaryKey(),
  email: varchar('email', { length: 255 }).notNull().unique(),
  password: varchar('password', { length: 255 }).notNull(),
  firstName: varchar('first_name', { length: 100 }).notNull(),
  lastName: varchar('last_name', { length: 100 }).notNull(),
  role: userRoleEnum('role').notNull(),
  status: userStatusEnum('status').default('PENDING_VERIFICATION').notNull(),
  company: varchar('company', { length: 255 }),
  phone: varchar('phone', { length: 50 }),
  avatar: text('avatar'),
  emailVerified: boolean('email_verified').default(false),
  emailVerificationToken: varchar('email_verification_token', { length: 255 }),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
});

// Projects Table
export const projects = pgTable('projects', {
  id: serial('id').primaryKey(),
  name: varchar('name', { length: 255 }).notNull(),
  description: text('description'),
  status: projectStatusEnum('status').default('planning').notNull(),
  projectNumber: varchar('project_number', { length: 100 }).notNull().unique(),

  // Location
  address: text('address'),
  city: varchar('city', { length: 100 }),
  state: varchar('state', { length: 2 }),
  zipCode: varchar('zip_code', { length: 10 }),

  // Budget
  totalBudget: integer('total_budget').default(0),
  spentBudget: integer('spent_budget').default(0),
  allocatedBudget: integer('allocated_budget').default(0),
  committedBudget: integer('committed_budget').default(0),
  remainingBudget: integer('remaining_budget').default(0),

  // Dates
  startDate: timestamp('start_date'),
  estimatedCompletion: timestamp('estimated_completion'),
  actualCompletion: timestamp('actual_completion'),

  // Team (storing IDs as JSON for flexibility)
  ownerId: integer('owner_id'),
  generalContractorId: integer('general_contractor_id'),
  teamMembers: jsonb('team_members').default('[]'),

  // Progress
  progressPercentage: integer('progress_percentage').default(0),
  completedMilestones: integer('completed_milestones').default(0),
  totalMilestones: integer('total_milestones').default(0),

  // Metadata
  tags: jsonb('tags').default('[]'),
  settings: jsonb('settings').default('{}'),
  createdBy: integer('created_by'),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
});

// Tasks Table
export const tasks = pgTable('tasks', {
  id: serial('id').primaryKey(),
  projectId: integer('project_id').notNull(),
  title: varchar('title', { length: 255 }).notNull(),
  description: text('description'),
  type: taskTypeEnum('type').default('general').notNull(),
  status: taskStatusEnum('status').default('pending').notNull(),
  priority: taskPriorityEnum('priority').default('medium').notNull(),

  // Assignment
  assignedTo: jsonb('assigned_to').default('[]').notNull(), // Array of user IDs
  assignedBy: integer('assigned_by'),

  // Dates
  dueDate: timestamp('due_date'),
  completedAt: timestamp('completed_at'),

  // Auto-generation
  autoGenerated: boolean('auto_generated').default(false),
  generatedFrom: jsonb('generated_from'), // {source: 'milestone', milestoneId: '...'}

  // Additional data
  checklist: jsonb('checklist').default('[]'),
  comments: jsonb('comments').default('[]'),
  tags: jsonb('tags').default('[]'),

  // Metadata
  createdBy: integer('created_by'),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
});

// Document-related enums
export const documentStatusEnum = pgEnum('document_status', ['draft', 'submitted', 'under_review', 'approved', 'rejected', 'closed']);
export const rfiStatusEnum = pgEnum('rfi_status', ['open', 'pending', 'answered', 'closed']);
export const changeOrderStatusEnum = pgEnum('change_order_status', ['proposed', 'approved', 'rejected', 'executed']);

// RFI (Requests for Information) Table
export const rfis = pgTable('rfis', {
  id: serial('id').primaryKey(),
  projectId: integer('project_id').notNull(),
  rfiNumber: varchar('rfi_number', { length: 50 }).notNull(), // e.g., RFI-001
  subject: varchar('subject', { length: 255 }).notNull(),
  description: text('description').notNull(),
  question: text('question').notNull(),

  // Status tracking
  status: rfiStatusEnum('status').default('open').notNull(),
  priority: taskPriorityEnum('priority').default('medium').notNull(),

  // People involved
  submittedBy: integer('submitted_by').notNull(),
  assignedTo: integer('assigned_to'), // Usually architect or designer

  // Response
  response: text('response'),
  respondedBy: integer('responded_by'),
  respondedAt: timestamp('responded_at'),

  // Related documents
  attachments: jsonb('attachments').default('[]'), // Array of file URLs
  linkedDocuments: jsonb('linked_documents').default('[]'),

  // Dates
  dueDate: timestamp('due_date'),
  closedAt: timestamp('closed_at'),

  // Metadata
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
});

// Change Orders Table
export const changeOrders = pgTable('change_orders', {
  id: serial('id').primaryKey(),
  projectId: integer('project_id').notNull(),
  changeOrderNumber: varchar('change_order_number', { length: 50 }).notNull(), // e.g., CO-001
  title: varchar('title', { length: 255 }).notNull(),
  description: text('description').notNull(),
  reason: text('reason').notNull(),

  // Cost impact
  costImpact: integer('cost_impact').default(0), // In cents
  originalCost: integer('original_cost').default(0),
  revisedCost: integer('revised_cost').default(0),

  // Schedule impact
  scheduleImpactDays: integer('schedule_impact_days').default(0),
  originalCompletion: timestamp('original_completion'),
  revisedCompletion: timestamp('revised_completion'),

  // Status and approval
  status: changeOrderStatusEnum('status').default('proposed').notNull(),

  // Workflow
  initiatedBy: integer('initiated_by').notNull(),
  approvedBy: integer('approved_by'),
  approvedAt: timestamp('approved_at'),

  // Related items
  attachments: jsonb('attachments').default('[]'),
  linkedRFIs: jsonb('linked_rfis').default('[]'),

  // Metadata
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
});

// Daily Reports Table
export const dailyReports = pgTable('daily_reports', {
  id: serial('id').primaryKey(),
  projectId: integer('project_id').notNull(),
  reportDate: timestamp('report_date').notNull(),

  // Weather
  weatherCondition: varchar('weather_condition', { length: 100 }),
  temperature: varchar('temperature', { length: 50 }),

  // Workforce
  workforceCount: jsonb('workforce_count').default('{}'), // {trade: count}
  totalWorkers: integer('total_workers').default(0),

  // Equipment
  equipmentUsed: jsonb('equipment_used').default('[]'), // Array of equipment

  // Work performed
  workPerformed: text('work_performed').notNull(),
  areasWorked: jsonb('areas_worked').default('[]'),

  // Issues and notes
  issues: text('issues'),
  safetyNotes: text('safety_notes'),
  visitorsOnSite: jsonb('visitors_on_site').default('[]'),

  // Materials
  materialsDelivered: jsonb('materials_delivered').default('[]'),

  // Photos
  photos: jsonb('photos').default('[]'), // Array of {url, caption, timestamp, location}

  // Metadata
  submittedBy: integer('submitted_by').notNull(),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
});

// Submittals Table
export const submittals = pgTable('submittals', {
  id: serial('id').primaryKey(),
  projectId: integer('project_id').notNull(),
  submittalNumber: varchar('submittal_number', { length: 50 }).notNull(),

  // Classification
  csiDivision: varchar('csi_division', { length: 10 }).notNull(), // e.g., "03", "04"
  specSection: varchar('spec_section', { length: 50 }),
  title: varchar('title', { length: 255 }).notNull(),
  description: text('description'),

  // Status and workflow
  status: documentStatusEnum('status').default('draft').notNull(),

  // Workflow: Sub → GC → Architect → Approval
  submittedBy: integer('submitted_by').notNull(), // Usually subcontractor
  reviewedByGC: integer('reviewed_by_gc'),
  gcReviewDate: timestamp('gc_review_date'),
  gcComments: text('gc_comments'),

  reviewedByArchitect: integer('reviewed_by_architect'),
  architectReviewDate: timestamp('architect_review_date'),
  architectComments: text('architect_comments'),

  // Final decision
  finalStatus: varchar('final_status', { length: 50 }), // Approved, Rejected, Approved as Noted, etc.
  approvedBy: integer('approved_by'),
  approvedAt: timestamp('approved_at'),

  // Documents
  attachments: jsonb('attachments').default('[]'),
  revisionHistory: jsonb('revision_history').default('[]'),

  // Dates
  dueDate: timestamp('due_date'),
  submittedDate: timestamp('submitted_date'),

  // Metadata
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
});

// File/Document enums
export const folderTypeEnum = pgEnum('folder_type', [
  'photos',
  'daily_reports',
  'certificates_insurance',
  'contracts',
  'submittals',
  'shop_drawings',
  'rfis',
  'change_orders',
  'plans_specs',
  'safety',
  'meeting_minutes',
  'warranties',
  'closeout',
  'general'
]);

// File Attachments Table
export const fileAttachments = pgTable('file_attachments', {
  id: serial('id').primaryKey(),
  projectId: integer('project_id').notNull(),

  // File information
  fileName: varchar('file_name', { length: 255 }).notNull(),
  originalName: varchar('original_name', { length: 255 }).notNull(),
  fileSize: integer('file_size').notNull(), // In bytes
  mimeType: varchar('mime_type', { length: 100 }).notNull(),
  fileUrl: text('file_url').notNull(), // S3 URL or local path

  // Organization
  folderType: folderTypeEnum('folder_type').notNull(),
  folderPath: varchar('folder_path', { length: 500 }), // e.g., "photos/2024/january"

  // Associations - what is this file attached to?
  relatedEntity: varchar('related_entity', { length: 50 }), // 'rfi', 'change_order', 'submittal', etc.
  relatedEntityId: integer('related_entity_id'),

  // Metadata
  description: text('description'),
  tags: jsonb('tags').default('[]'),
  uploadedBy: integer('uploaded_by').notNull(),

  // Versioning
  version: integer('version').default(1),
  isLatestVersion: boolean('is_latest_version').default(true),
  replacesFileId: integer('replaces_file_id'), // If this is a new version of another file

  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
});

// Activity Log Table - Track all project communications and changes
export const activityLog = pgTable('activity_log', {
  id: serial('id').primaryKey(),
  projectId: integer('project_id').notNull(),

  // What happened?
  action: varchar('action', { length: 100 }).notNull(), // 'created', 'updated', 'deleted', 'uploaded', 'commented', etc.
  entityType: varchar('entity_type', { length: 50 }).notNull(), // 'rfi', 'change_order', 'file', 'project', etc.
  entityId: integer('entity_id'),

  // Description of the activity
  description: text('description').notNull(),
  changes: jsonb('changes'), // Store before/after values for updates

  // Who did it?
  userId: integer('user_id').notNull(),
  userName: varchar('user_name', { length: 255 }), // Denormalized for performance
  userRole: varchar('user_role', { length: 50 }),

  // Additional context
  metadata: jsonb('metadata').default('{}'),
  ipAddress: varchar('ip_address', { length: 45 }),

  createdAt: timestamp('created_at').defaultNow().notNull(),
});

// Comments Table - For discussions on any entity
export const comments = pgTable('comments', {
  id: serial('id').primaryKey(),
  projectId: integer('project_id').notNull(),

  // What is being commented on?
  entityType: varchar('entity_type', { length: 50 }).notNull(),
  entityId: integer('entity_id').notNull(),

  // Comment content
  content: text('content').notNull(),
  attachments: jsonb('attachments').default('[]'), // Array of file IDs

  // Threading support
  parentCommentId: integer('parent_comment_id'), // For replies

  // Author
  authorId: integer('author_id').notNull(),
  authorName: varchar('author_name', { length: 255 }),

  // Status
  isEdited: boolean('is_edited').default(false),
  isDeleted: boolean('is_deleted').default(false),

  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
});

// Type exports for TypeScript
export type User = typeof users.$inferSelect;
export type NewUser = typeof users.$inferInsert;
export type Project = typeof projects.$inferSelect;
export type NewProject = typeof projects.$inferInsert;
export type Task = typeof tasks.$inferSelect;
export type NewTask = typeof tasks.$inferInsert;
export type RFI = typeof rfis.$inferSelect;
export type NewRFI = typeof rfis.$inferInsert;
export type ChangeOrder = typeof changeOrders.$inferSelect;
export type NewChangeOrder = typeof changeOrders.$inferInsert;
export type DailyReport = typeof dailyReports.$inferSelect;
export type NewDailyReport = typeof dailyReports.$inferInsert;
export type Submittal = typeof submittals.$inferSelect;
export type NewSubmittal = typeof submittals.$inferInsert;
export type FileAttachment = typeof fileAttachments.$inferSelect;
export type NewFileAttachment = typeof fileAttachments.$inferInsert;
export type ActivityLog = typeof activityLog.$inferSelect;
export type NewActivityLog = typeof activityLog.$inferInsert;
export type Comment = typeof comments.$inferSelect;
export type NewComment = typeof comments.$inferInsert;
