/**
 * To-Do List Widget Component
 * Displays user's tasks with auto-population from milestones
 * Filters by priority and due date
 */
import { createSignal, createEffect, For, Show } from 'solid-js';
import type { Task } from '../../lib/db/schemas/Task';
import { TaskStatus, TaskType, TaskPriority } from '../../lib/db/schemas/Task';

interface TodoListWidgetProps {
  userId: string;
}

export default function TodoListWidget(props: TodoListWidgetProps) {
  const [tasks, setTasks] = createSignal<Task[]>([]);
  const [loading, setLoading] = createSignal(true);
  const [filter, setFilter] = createSignal<'all' | 'today' | 'week'>('today');

  // Fetch tasks on component mount
  createEffect(async () => {
    try {
      setLoading(true);
      const response = await fetch(`/api/tasks?userId=${props.userId}&filter=${filter()}`);

      if (!response.ok) {
        throw new Error('Failed to fetch tasks');
      }

      const data = await response.json();
      setTasks(data.tasks || []);
    } catch (err) {
      console.error('Error fetching tasks:', err);
      // Show sample tasks if API fails (for development)
      setTasks([
        {
          _id: '1',
          projectId: 'proj-1',
          title: 'Submit RFI for plumbing fixture specifications',
          type: TaskType.RFI,
          status: TaskStatus.PENDING,
          priority: TaskPriority.HIGH,
          assignedTo: [props.userId],
          assignedBy: 'gc-user-id',
          dueDate: new Date(Date.now() + 86400000), // Tomorrow
          autoGenerated: true,
          generatedFrom: { source: 'milestone' as const, milestoneId: 'milestone-1' },
          createdBy: 'system',
          createdAt: new Date(),
          updatedAt: new Date(),
          tags: []
        },
        {
          _id: '2',
          projectId: 'proj-1',
          title: 'Review electrical submittal package',
          type: TaskType.SUBMITTAL,
          status: TaskStatus.PENDING,
          priority: TaskPriority.MEDIUM,
          assignedTo: [props.userId],
          assignedBy: 'gc-user-id',
          dueDate: new Date(Date.now() + 172800000), // 2 days
          autoGenerated: false,
          createdBy: 'gc-user-id',
          createdAt: new Date(),
          updatedAt: new Date(),
          tags: []
        },
        {
          _id: '3',
          projectId: 'proj-2',
          title: 'Schedule pre-construction meeting',
          type: TaskType.GENERAL,
          status: TaskStatus.IN_PROGRESS,
          priority: TaskPriority.URGENT,
          assignedTo: [props.userId],
          assignedBy: 'owner-user-id',
          dueDate: new Date(Date.now() + 43200000), // 12 hours
          autoGenerated: false,
          createdBy: 'owner-user-id',
          createdAt: new Date(),
          updatedAt: new Date(),
          tags: []
        }
      ] as Task[]);
    } finally {
      setLoading(false);
    }
  });

  // Toggle task completion
  const toggleTask = async (taskId: string) => {
    const task = tasks().find(t => t._id === taskId);
    if (!task) return;

    const newStatus = task.status === TaskStatus.COMPLETED ? TaskStatus.PENDING : TaskStatus.COMPLETED;

    try {
      await fetch(`/api/tasks/${taskId}`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ status: newStatus })
      });

      // Update local state
      setTasks(tasks().map(t =>
        t._id === taskId ? { ...t, status: newStatus } : t
      ));
    } catch (error) {
      console.error('Error updating task:', error);
    }
  };

  // Get priority badge color
  const getPriorityColor = (priority: string) => {
    const colors: Record<string, string> = {
      'urgent': 'bg-red-100 text-red-800',
      'high': 'bg-orange-100 text-orange-800',
      'medium': 'bg-yellow-100 text-yellow-800',
      'low': 'bg-green-100 text-green-800',
    };
    return colors[priority] || 'bg-gray-100 text-gray-800';
  };

  // Format due date
  const formatDueDate = (dueDate: Date | undefined) => {
    if (!dueDate) return '';
    const date = new Date(dueDate);
    const today = new Date();
    const tomorrow = new Date(today);
    tomorrow.setDate(tomorrow.getDate() + 1);

    if (date.toDateString() === today.toDateString()) {
      return 'Today';
    } else if (date.toDateString() === tomorrow.toDateString()) {
      return 'Tomorrow';
    } else {
      return date.toLocaleDateString();
    }
  };

  // Check if task is overdue
  const isOverdue = (dueDate: Date | undefined) => {
    if (!dueDate) return false;
    return new Date(dueDate) < new Date();
  };

  return (
    <div>
      {/* Filter Tabs */}
      <div class="flex space-x-2 mb-4">
        <button
          onClick={() => setFilter('today')}
          class={`px-3 py-1 text-sm rounded-md ${
            filter() === 'today'
              ? 'bg-primary-orange text-white'
              : 'bg-gray-100 text-text-secondary hover:bg-gray-200'
          }`}
        >
          Today
        </button>
        <button
          onClick={() => setFilter('week')}
          class={`px-3 py-1 text-sm rounded-md ${
            filter() === 'week'
              ? 'bg-primary-orange text-white'
              : 'bg-gray-100 text-text-secondary hover:bg-gray-200'
          }`}
        >
          This Week
        </button>
        <button
          onClick={() => setFilter('all')}
          class={`px-3 py-1 text-sm rounded-md ${
            filter() === 'all'
              ? 'bg-primary-orange text-white'
              : 'bg-gray-100 text-text-secondary hover:bg-gray-200'
          }`}
        >
          All
        </button>
      </div>

      {/* Loading State */}
      <Show when={loading()}>
        <div class="text-center py-4">
          <div class="inline-block animate-spin rounded-full h-6 w-6 border-4 border-primary-orange border-t-transparent"></div>
        </div>
      </Show>

      {/* Task List */}
      <Show when={!loading()}>
        <Show
          when={tasks().length > 0}
          fallback={
            <div class="text-center py-6 text-text-secondary">
              <p class="text-sm">No tasks for this period.</p>
              <p class="text-xs mt-1">You're all caught up!</p>
            </div>
          }
        >
          <div class="space-y-3 max-h-96 overflow-y-auto pr-2">
            <For each={tasks()}>
              {(task) => (
                <div class="border border-gray-200 rounded-lg p-3 hover:shadow-ca-sm transition-shadow">
                  {/* Task Header */}
                  <div class="flex items-start space-x-3">
                    <input
                      type="checkbox"
                      checked={task.status === TaskStatus.COMPLETED}
                      onChange={() => toggleTask(task._id)}
                      class="mt-1 w-4 h-4 text-primary-orange border-gray-300 rounded focus:ring-primary-orange cursor-pointer"
                    />
                    <div class="flex-1 min-w-0">
                      <p
                        class={`text-sm font-medium ${
                          task.status === TaskStatus.COMPLETED
                            ? 'line-through text-text-secondary'
                            : 'text-text-primary'
                        }`}
                      >
                        {task.title}
                      </p>

                      {/* Task Meta */}
                      <div class="flex items-center space-x-2 mt-1">
                        <span class={`text-xs px-2 py-0.5 rounded-full ${getPriorityColor(task.priority)}`}>
                          {task.priority}
                        </span>
                        {task.dueDate && (
                          <span
                            class={`text-xs ${
                              isOverdue(task.dueDate) && task.status !== TaskStatus.COMPLETED
                                ? 'text-red-600 font-semibold'
                                : 'text-text-secondary'
                            }`}
                          >
                            📅 {formatDueDate(task.dueDate)}
                          </span>
                        )}
                        {task.autoGenerated && (
                          <span class="text-xs text-blue-600" title="Auto-generated from project milestone">
                            🤖 Auto
                          </span>
                        )}
                      </div>
                    </div>
                  </div>
                </div>
              )}
            </For>
          </div>

          {/* View All Link */}
          <div class="mt-4 text-center">
            <a href="/tasks" class="text-sm text-primary-orange hover:underline font-medium">
              View All Tasks →
            </a>
          </div>
        </Show>
      </Show>

      {/* Add Task Button */}
      <button class="w-full mt-4 px-4 py-2 border-2 border-dashed border-gray-300 rounded-md text-text-secondary hover:border-primary-orange hover:text-primary-orange transition-colors text-sm">
        + Add New Task
      </button>
    </div>
  );
}
