#!/usr/bin/env python3
"""
Task Generator Script for ConstructAid
Auto-generates tasks from project schedules and milestones

This script analyzes project schedules and automatically creates tasks
for team members based on milestones, dependencies, and timelines.

Usage:
    python scripts/task_generator.py --project-id <project_id>
    python scripts/task_generator.py --project-id <project_id> --milestone-id <milestone_id>

Requirements:
    - pymongo: MongoDB Python driver
    - pandas: Data analysis
    - python-dotenv: Environment variable management
"""

import argparse
import sys
from datetime import datetime, timedelta
from typing import List, Dict, Optional
import os
from dotenv import load_dotenv

try:
    from pymongo import MongoClient
    import pandas as pd
except ImportError:
    print("Error: Required packages not installed.")
    print("Please run: pip install pymongo pandas python-dotenv")
    sys.exit(1)

# Load environment variables
load_dotenv()

# MongoDB connection
MONGODB_URI = os.getenv('MONGODB_URI', 'mongodb://localhost:27017')
DB_NAME = os.getenv('MONGODB_DB_NAME', 'constructaid')


class TaskGenerator:
    """Generates tasks from project milestones and schedules"""

    def __init__(self, project_id: str):
        """
        Initialize TaskGenerator

        Args:
            project_id: MongoDB ObjectId of the project
        """
        self.project_id = project_id
        self.client = MongoClient(MONGODB_URI)
        self.db = self.client[DB_NAME]
        self.projects = self.db['projects']
        self.tasks = self.db['tasks']
        self.users = self.db['users']

    def close(self):
        """Close database connection"""
        self.client.close()

    def get_project(self) -> Optional[Dict]:
        """Fetch project data from database"""
        project = self.projects.find_one({'_id': self.project_id})
        if not project:
            print(f"Error: Project {self.project_id} not found")
            return None
        return project

    def generate_milestone_tasks(self, milestone: Dict, project: Dict) -> List[Dict]:
        """
        Generate tasks from a milestone

        Args:
            milestone: Milestone object from project
            project: Full project document

        Returns:
            List of task documents to insert
        """
        tasks = []
        milestone_date = milestone.get('dueDate')
        milestone_name = milestone.get('name', '')

        # Define task templates based on milestone type
        task_templates = self._get_task_templates(milestone_name)

        for template in task_templates:
            # Calculate task due date (offset from milestone date)
            task_due_date = milestone_date - timedelta(days=template['days_before'])

            # Determine assignee based on role
            assignees = self._get_assignees_by_role(project, template['role'])

            if not assignees:
                print(f"Warning: No assignees found for role {template['role']}")
                continue

            task = {
                'projectId': self.project_id,
                'title': template['title'].format(milestone_name=milestone_name),
                'description': template.get('description', ''),
                'type': template.get('type', 'general'),
                'status': 'pending',
                'priority': template.get('priority', 'medium'),
                'assignedTo': assignees,
                'assignedBy': project['team']['generalContractor'],
                'dueDate': task_due_date,
                'milestoneId': milestone.get('id'),
                'autoGenerated': True,
                'generatedFrom': {
                    'source': 'milestone',
                    'milestoneId': milestone.get('id')
                },
                'checklist': template.get('checklist', []),
                'createdBy': 'system',
                'createdAt': datetime.utcnow(),
                'updatedAt': datetime.utcnow(),
                'tags': ['auto-generated', 'milestone']
            }

            tasks.append(task)

        return tasks

    def _get_task_templates(self, milestone_name: str) -> List[Dict]:
        """
        Get task templates based on milestone type

        Args:
            milestone_name: Name of the milestone

        Returns:
            List of task template dictionaries
        """
        milestone_lower = milestone_name.lower()

        # Common construction milestone templates
        if 'foundation' in milestone_lower:
            return [
                {
                    'title': 'Submit RFI for foundation specifications',
                    'type': 'RFI',
                    'priority': 'high',
                    'role': 'GC',
                    'days_before': 14,
                    'description': 'Submit RFI to clarify foundation specifications before {milestone_name}'
                },
                {
                    'title': 'Schedule soil testing',
                    'type': 'inspection',
                    'priority': 'high',
                    'role': 'GC',
                    'days_before': 21,
                    'description': 'Coordinate with geotechnical engineer for soil testing'
                },
                {
                    'title': 'Order foundation materials',
                    'type': 'general',
                    'priority': 'medium',
                    'role': 'GC',
                    'days_before': 10,
                    'description': 'Ensure concrete and rebar materials are ordered and scheduled for delivery'
                }
            ]
        elif 'framing' in milestone_lower or 'structure' in milestone_lower:
            return [
                {
                    'title': 'Submit structural steel shop drawings',
                    'type': 'submittal',
                    'priority': 'high',
                    'role': 'SUB',
                    'days_before': 30,
                    'description': 'Prepare and submit structural shop drawings for approval'
                },
                {
                    'title': 'Coordinate framing schedule with MEP trades',
                    'type': 'general',
                    'priority': 'medium',
                    'role': 'GC',
                    'days_before': 14,
                    'description': 'Schedule coordination meeting with MEP subcontractors'
                }
            ]
        elif 'mechanical' in milestone_lower or 'mep' in milestone_lower or 'hvac' in milestone_lower:
            return [
                {
                    'title': 'Submit HVAC equipment submittals',
                    'type': 'submittal',
                    'priority': 'high',
                    'role': 'SUB',
                    'days_before': 45,
                    'description': 'Submit HVAC equipment specifications and cut sheets'
                },
                {
                    'title': 'Coordinate MEP routing with architect',
                    'type': 'general',
                    'priority': 'medium',
                    'role': 'GC',
                    'days_before': 21,
                    'description': 'Schedule coordination meeting to finalize MEP routing'
                }
            ]
        elif 'plumbing' in milestone_lower:
            return [
                {
                    'title': 'Submit plumbing fixture specifications',
                    'type': 'submittal',
                    'priority': 'high',
                    'role': 'SUB',
                    'days_before': 30,
                    'description': 'Submit plumbing fixture cut sheets and specifications'
                },
                {
                    'title': 'Schedule rough plumbing inspection',
                    'type': 'inspection',
                    'priority': 'high',
                    'role': 'GC',
                    'days_before': 7,
                    'description': 'Coordinate with building department for rough plumbing inspection'
                }
            ]
        elif 'electrical' in milestone_lower:
            return [
                {
                    'title': 'Submit electrical panel schedule',
                    'type': 'submittal',
                    'priority': 'high',
                    'role': 'SUB',
                    'days_before': 30,
                    'description': 'Prepare and submit electrical panel schedules'
                },
                {
                    'title': 'Coordinate power requirements with utility company',
                    'type': 'general',
                    'priority': 'medium',
                    'role': 'GC',
                    'days_before': 45,
                    'description': 'Confirm power availability and schedule utility connections'
                }
            ]
        elif 'closeout' in milestone_lower or 'completion' in milestone_lower:
            return [
                {
                    'title': 'Compile closeout documentation',
                    'type': 'general',
                    'priority': 'high',
                    'role': 'GC',
                    'days_before': 30,
                    'description': 'Gather all warranties, O&M manuals, and as-built drawings'
                },
                {
                    'title': 'Schedule final inspection',
                    'type': 'inspection',
                    'priority': 'high',
                    'role': 'GC',
                    'days_before': 14,
                    'description': 'Coordinate final building inspection with authorities'
                },
                {
                    'title': 'Prepare punch list',
                    'type': 'general',
                    'priority': 'medium',
                    'role': 'GC',
                    'days_before': 21,
                    'description': 'Walk project with owner/architect to create punch list'
                }
            ]
        else:
            # Generic milestone tasks
            return [
                {
                    'title': f'Prepare for {milestone_name}',
                    'type': 'general',
                    'priority': 'medium',
                    'role': 'GC',
                    'days_before': 7,
                    'description': f'Complete all preparations for {milestone_name}'
                }
            ]

    def _get_assignees_by_role(self, project: Dict, role: str) -> List[str]:
        """
        Get user IDs for a specific role in the project

        Args:
            project: Project document
            role: Role code (GC, SUB, ARCHITECT, OWNER)

        Returns:
            List of user IDs
        """
        team = project.get('team', {})

        if role == 'GC':
            gc = team.get('generalContractor')
            return [gc] if gc else []
        elif role == 'SUB':
            # Return all subcontractors
            subs = team.get('subcontractors', [])
            return [sub['userId'] for sub in subs]
        elif role == 'ARCHITECT':
            return team.get('architects', [])
        elif role == 'OWNER':
            owner = team.get('owner')
            return [owner] if owner else []
        else:
            return []

    def run(self, milestone_id: Optional[str] = None) -> int:
        """
        Run task generation

        Args:
            milestone_id: Optional - Generate tasks for specific milestone only

        Returns:
            Number of tasks generated
        """
        print(f"Generating tasks for project: {self.project_id}")

        # Fetch project
        project = self.get_project()
        if not project:
            return 0

        # Get milestones
        milestones = project.get('dates', {}).get('milestones', [])

        if not milestones:
            print("No milestones found for this project")
            return 0

        # Filter milestones if specific ID provided
        if milestone_id:
            milestones = [m for m in milestones if m.get('id') == milestone_id]
            if not milestones:
                print(f"Milestone {milestone_id} not found")
                return 0

        # Generate tasks for each milestone
        all_tasks = []
        for milestone in milestones:
            if milestone.get('completed'):
                print(f"Skipping completed milestone: {milestone.get('name')}")
                continue

            print(f"Generating tasks for milestone: {milestone.get('name')}")
            tasks = self.generate_milestone_tasks(milestone, project)
            all_tasks.extend(tasks)

        # Insert tasks into database
        if all_tasks:
            result = self.tasks.insert_many(all_tasks)
            print(f"✓ Successfully generated {len(result.inserted_ids)} tasks")
            return len(result.inserted_ids)
        else:
            print("No tasks to generate")
            return 0


def main():
    """Main function"""
    parser = argparse.ArgumentParser(description='Generate tasks from project milestones')
    parser.add_argument('--project-id', required=True, help='Project ID (MongoDB ObjectId)')
    parser.add_argument('--milestone-id', help='Specific milestone ID (optional)')

    args = parser.parse_args()

    # Create generator
    generator = TaskGenerator(args.project_id)

    try:
        # Run task generation
        count = generator.run(milestone_id=args.milestone_id)
        print(f"\nTask generation complete. {count} tasks created.")
    except Exception as e:
        print(f"Error: {e}")
        sys.exit(1)
    finally:
        generator.close()


if __name__ == '__main__':
    main()
